In [1]:
import meshio
from stl import mesh 
import numpy as np 

In [23]:
# get mesh information 
stl_file_path = "C://Users//Acer//Downloads//ct_0096_label.nii//label_8_pulmonary_trunk.stl"
obj_file_path = "output_file.obj"

mesh = meshio.read(stl_file_path)

newMesh = meshio.Mesh(mesh.points, mesh.cells) 

In [24]:
# recenter mesh 
def recenter_mesh(mesh): 
    offset = -np.mean(mesh.points, axis=0)
    mesh.points = mesh.points + offset

recenter_mesh(newMesh)

In [25]:
meshio.write(obj_file_path, newMesh)

In [3]:
# data field is list of faces representing the index of vertices in list of vertices
cellblock = mesh.cells[0]
data = cellblock.data

for i in range(6): 
    print(data[i])

[0 1 2]
[0 3 4]
[1 0 4]
[3 5 6]
[4 3 6]
[6 5 7]


In [4]:
triangles = [] 

for face in data: 
    triangles.append(face[0])
    triangles.append(face[1])
    triangles.append(face[2])

In [5]:
# access the individual indices
for i in range(6):
    print(triangles[i] + 1)

1
2
3
1
4
5


In [13]:
# mesh.points represent all the vertices that are already in the order for mesh reconstruction 
with open("output.txt", "w") as f: 
    f.write("v\n")
    for point in mesh.points: 
        f.write(f"{point[0]} {point[1]} {point[2]}\n")
    
    f.write("t\n") 

    for i in range(0, len(triangles), 3): 
        f.write(f"{triangles[i]} {triangles[i + 1]} {triangles[i + 2]}\n")