In [ ]:
'''
    6--------7
   /|       /|
  / |      / |
 2--------3  |
 |  |     |  |
 |  4-----|--5
 | /      | /
 |/       |/
 0--------1
'''

In [3]:
import numpy as np

# Define the cube configuration and edge table
cube_configurations = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [0, 1, 5, 4],
    [2, 3, 7, 6],
    [0, 4, 7, 3],
    [1, 5, 6, 2]
], dtype=int)

In [6]:
edge_table = np.array([
    0x0, 0x109, 0x203, 0x30a, 0x406, 0x50f, 0x605, 0x70c,
    0x80c, 0x905, 0xa0f, 0xb06, 0xc0a, 0xd03, 0xe09, 0xf00,
    0x190, 0x99, 0x393, 0x29a, 0x596, 0x49f, 0x795, 0x69c,
    0x99c, 0x895, 0xb9f, 0xa96, 0xd9a, 0xc93, 0xf99, 0xe90,
    0x230, 0x339, 0x33, 0x13a, 0x636, 0x73f, 0x435, 0x53c,
    0xa3c, 0xb35, 0x83f, 0x936, 0xe3a, 0xf33, 0xc39, 0xd30,
    0x3a0, 0x2a9, 0x1a3, 0xaa, 0x7a6, 0x6af, 0x5a5, 0x4ac,
    0xbac, 0xaa5, 0x9af, 0x8a6, 0xfaa, 0xea3, 0xda9, 0xca0,
    0x460, 0x569, 0x663, 0x76a, 0x66, 0x16f, 0x265, 0x36c,
    0xc6c, 0xd65, 0xe6f, 0xf66, 0x86a, 0x963, 0xa69, 0xb60,
    0x5f0, 0x4f9, 0x7f3, 0x6fa, 0x1f6, 0xff, 0x3f5, 0x2fc,
    0xdfc, 0xcf5, 0xfff, 0xef6, 0x9fa, 0x8f3, 0xbf9, 0xaf0,
    0x650, 0x759, 0x453, 0x55a, 0x256, 0x35f, 0x55, 0x15c,
    0xe5c, 0xf55, 0xc5f, 0xd56, 0xa5a, 0xb53, 0x859, 0x950,
    0x7c0, 0x6c9, 0x5c3, 0x4ca, 0x3c6, 0x2cf, 0x1c5, 0xcc,
    0xfcc, 0xec5, 0xdcf, 0xcc6, 0xbca, 0xac3, 0x9c9, 0x8c0,
    0x8c0, 0x9c9, 0xac3, 0xbca, 0xcc6, 0xdcf, 0xec5, 0xfcc,
    0xcc, 0x1c5, 0x2cf, 0x3c6, 0x4ca, 0x5c3, 0x6c9, 0x7c0,
    0x950, 0x859, 0xb53, 0xa5a, 0xd56, 0xc5f, 0xf55, 0xe5c,
    0x15c, 0x55, 0x35f, 0x256, 0x55a, 0x453, 0x759, 0x650,
    0xaf0, 0xbf9, 0x8f3, 0x9fa, 0xef6, 0xfff, 0xcf5, 0xdfc,
    0x2fc, 0x3f5, 0xff, 0x1f6, 0x6fa, 0x7f3, 0x4f9, 0x5f0,
    0xb60, 0xa69, 0x963, 0x86a, 0xf66, 0xe6f, 0xd65, 0xc6c,
    0x36c, 0x265, 0x16f, 0x66, 0x76a, 0x663, 0x569, 0x460,
    0xca0, 0xda9, 0xea3, 0xfaa, 0x8a6, 0x9af, 0xaa5, 0xbac,
    0x4ac, 0x5a5, 0x6af, 0x7a6, 0xaa, 0x1a3, 0x2a9, 0x3a0,
    0xd30, 0xc39, 0xf33, 0xe3a, 0x936, 0x83f, 0xb35, 0xa3c,
    0x53c, 0x435, 0x73f, 0x636, 0x13a, 0x33, 0x339, 0x230,
    0xe90, 0xf99, 0xc93, 0xd9a, 0xa96, 0xb9f, 0x895, 0x99c,
    0x69c, 0x795, 0x49f, 0x596, 0x29a, 0x393, 0x99, 0x190,
    0xf00, 0xe09, 0xd03, 0xc0a, 0xb06, 0xa0f, 0x905, 0x80c,
    0x70c, 0x605, 0x50f, 0x406, 0x30a, 0x203, 0x109, 0x0
], dtype=np.uint32)

In [11]:
def interpolate(v1, v2, threshold):
    # Interpolate between two points based on the threshold
    if np.abs(threshold - v1) < 1e-5:
        return 0.5
    if np.abs(threshold - v2) < 1e-5:
        return 0.5
    if np.abs(v1 - v2) < 1e-5:
        return 0.5
    return (threshold - v1) / (v2 - v1)

In [12]:
def marching_cubes(scalar_field, threshold):
    vertices = []
    for i in range(len(scalar_field) - 1):
        for j in range(len(scalar_field[i]) - 1):
            for k in range(len(scalar_field[i][j]) - 1):
                cube_index = 0
                if scalar_field[i][j][k] < threshold:
                    cube_index |= 1
                if scalar_field[i + 1][j][k] < threshold:
                    cube_index |= 2
                if scalar_field[i + 1][j + 1][k] < threshold:
                    cube_index |= 4
                if scalar_field[i][j + 1][k] < threshold:
                    cube_index |= 8
                if scalar_field[i][j][k + 1] < threshold:
                    cube_index |= 16
                if scalar_field[i + 1][j][k + 1] < threshold:
                    cube_index |= 32
                if scalar_field[i + 1][j + 1][k + 1] < threshold:
                    cube_index |= 64
                if scalar_field[i][j + 1][k + 1] < threshold:
                    cube_index |= 128

                # Inside or outside completely
                if cube_index == 0 or cube_index == 255:
                    continue

                edge_flags = edge_table[cube_index]
                vertices_on_edges = []
                for edge in range(12):
                    if edge_flags & (1 << edge):
                        # v1, v2 = cube_configurations[edge]
                        vertices_on_edges.append(
                            (interpolate(scalar_field[i][j][k], scalar_field[i + 1][j][k], threshold) * np.array([i, j, k]) +
                             interpolate(scalar_field[i][j][k], scalar_field[i][j + 1][k], threshold) * np.array([i, j, k + 1]) +
                             interpolate(scalar_field[i][j][k], scalar_field[i][j][k + 1], threshold) * np.array([i, j + 1, k]) +
                             interpolate(scalar_field[i][j][k], scalar_field[i][j + 1][k + 1], threshold) * np.array([i, j + 1, k + 1]) +
                             interpolate(scalar_field[i + 1][j][k], scalar_field[i + 1][j + 1][k], threshold) * np.array([i + 1, j, k]) +
                             interpolate(scalar_field[i + 1][j][k], scalar_field[i + 1][j][k + 1], threshold) * np.array([i + 1, j, k + 1]) +
                             interpolate(scalar_field[i + 1][j][k], scalar_field[i + 1][j + 1][k + 1], threshold) * np.array([i + 1, j + 1, k + 1]) +
                             interpolate(scalar_field[i + 1][j + 1][k], scalar_field[i + 1][j + 1][k + 1], threshold) * np.array([i + 1, j + 1, k]) +
                             interpolate(scalar_field[i][j][k + 1], scalar_field[i + 1][j][k + 1], threshold) * np.array([i, j, k + 1]) +
                             interpolate(scalar_field[i][j + 1][k], scalar_field[i + 1][j + 1][k], threshold) * np.array([i, j + 1, k]) +
                             interpolate(scalar_field[i][j + 1][k + 1], scalar_field[i + 1][j + 1][k + 1], threshold) * np.array([i, j + 1, k + 1]) +
                             interpolate(scalar_field[i][j][k + 1], scalar_field[i][j + 1][k + 1], threshold) * np.array([i, j, k + 1]) +
                             interpolate(scalar_field[i][j][k], scalar_field[i + 1][j][k], threshold) * np.array([i + 1, j, k])
                             ) / 4)
                vertices.extend(vertices_on_edges)
    return vertices

In [13]:
# Example usage
scalar_field = np.random.rand(5, 5, 5)  # Replace with your own scalar field data
threshold = 0.5  # Set your threshold value
vertices = marching_cubes(scalar_field, threshold)
print("Number of vertices:", len(vertices))

Number of vertices: 342


In [14]:
vertices

[array([0.98231261, 6.26930284, 7.24917845]),
 array([0.98231261, 6.26930284, 7.24917845]),
 array([0.98231261, 6.26930284, 7.24917845]),
 array([0.98231261, 6.26930284, 7.24917845]),
 array([0.28577448, 0.75395485, 5.2475067 ]),
 array([0.28577448, 0.75395485, 5.2475067 ]),
 array([0.28577448, 0.75395485, 5.2475067 ]),
 array([0.28577448, 0.75395485, 5.2475067 ]),
 array([0.28577448, 0.75395485, 5.2475067 ]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([1.34478767, 1.50068799, 0.48699978]),
 array([-0.44873064,  6.293322  ,  6.9347667 ]),
 array([-0.44873064,  6.293322  ,  6.9347667 ]),
 array([-0.44873064,  6.293322  ,  6.9347667 ]),
 array([-0.44873064,  6.293322  ,  6.9347667 ]),
 array([-0.44873064,  6.293322  ,  6.9347667 ]),
 array([ 5.58932663, 11.05665491,  9.65328402]),
 array([ 5.58932

In [17]:
import numpy as np
from skimage import measure
from stl import mesh

# Define parameters
resolution = 5  
radius = 1.0  
threshold = 0.5 

# Create grid coordinates
x = np.linspace(-radius, radius, resolution)
y = np.linspace(-radius, radius, resolution)
z = np.linspace(-radius, radius, resolution)
X, Y, Z = np.meshgrid(x, y, z)

# Create sphere using implicit equation
sphere = X**2 + Y**2 + Z**2

# Extract vertices and faces using marching cubes
verts, faces, _, _ = measure.marching_cubes(sphere, threshold)

# Create mesh object
mesh_data = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
        mesh_data.vectors[i][j] = verts[f[j], :]

# Save mesh to STL file
mesh_data.save('sphere.stl')

In [20]:
x = np.linspace(-radius, radius, resolution)
y = np.linspace(-radius, radius, resolution)
z = np.linspace(-radius, radius, resolution)

print(x)
print(y)
print(z)

[-1.  -0.5  0.   0.5  1. ]
[-1.  -0.5  0.   0.5  1. ]
[-1.  -0.5  0.   0.5  1. ]


In [21]:
X, Y, Z = np.meshgrid(x, y, z)

sphere = X**2 + Y**2 + Z**2

In [25]:
X.shape, Y.shape, Z.shape

((5, 5, 5), (5, 5, 5), (5, 5, 5))

In [30]:
print(X[0][0][0])
print(Y[0][0][0])
print(Z[0][0][0])

-1.0
-1.0
-1.0


In [35]:
import plotly.express as px
import plotly.graph_objects as go

def ShowGraph(x,y,z):
  fig = go.Figure(data=[go.Surface(x=x,y=y,z=z)])
  fig.update_layout(
        title="z = f(x,y)",
        scene=dict(xaxis_title='x', yaxis_title='Y', zaxis_title='Z')
    )
  fig.show()

In [ ]:
ShowGraph(X,Y,Z)